export { default as TrashIcon } from "./TrashIcon";
export { default as SendIcon } from "./SendIcon";
export { default as GoogleLogo } from "./GoogleLogo";
export { default as LadderIcon } from "./LadderIcon";
export { default as Phone } from "./Phone";
export { default as CloseIcon } from "./CloseIcon";
export { default as MicrophoneIcon } from "./MicrophoneIcon";
export { default as BackIcon } from "./BackIcon";
export { default as ClockIcon } from "./ClockIcon";
export { default as EmailIcon } from "./EmailIcon";
export { default as AccountIcon } from "./AccountIcon";
export { default as ChatIcon } from "./ChatIcon";
export { default as HistoryIcon } from "./HistoryIcon";
export { default as StudyIcon } from "./StudyIcon";
export { default as ProfileIcon } from "./ProfileIcon";

// topics icons
export { default as FoodIcon } from "./topics/FoodIcon";
export { default as MoviesIcon } from "./topics/MoviesIcon";
export { default as ArtIcon } from "./topics/ArtIcon";
export { default as PoliticsIcon } from "./topics/PoliticsIcon";
export { default as WorkIcon } from "./topics/WorkIcon";
export { default as SchoolIcon } from "./topics/SchoolIcon";
export { default as TravelIcon } from "./topics/TravelIcon";
export { default as MusicIcon } from "./topics/MusicIcon";
export { default as ActivitiesIcon } from "./topics/ActivitiesIcon";
export { default as SportsIcon } from "./topics/SportsIcon";
export { default as WeatherIcon } from "./topics/WeatherIcon";
export { default as TechIcon } from "./topics/TechIcon";
export { default as RandomIcon } from "./topics/RandomIcon";
export { default as FamilyIcon } from "./topics/FamilyIcon";
export { default as RelationshipsIcon } from "./topics/RelationshipsIcon";

// language icons
export { default as EnglishIcon } from "./languages/EnglishIcon";
export { default as SpanishIcon } from "./languages/SpanishIcon";
export { default as FrenchIcon } from "./languages/FrenchIcon";
export { default as GermanIcon } from "./languages/GermanIcon";
export { default as ItalianIcon } from "./languages/ItalianIcon";
export { default as PortugueseIcon } from "./languages/PortugueseIcon";
export { default as ArabicIcon } from "./languages/ArabicIcon";
export { default as ChineseIcon } from "./languages/ChineseIcon";
export { default as JapaneseIcon } from "./languages/JapaneseIcon";
export { default as KoreanIcon } from "./languages/KoreanIcon";
export { default as RussianIcon } from "./languages/RussianIcon";
export { default as DutchIcon } from "./languages/DutchIcon";
export { default as HindiIcon } from "./languages/HindiIcon";
export { default as TurkishIcon } from "./languages/TurkishIcon";
export { default as SwahiliIcon } from "./languages/SwahiliIcon";
